server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    charset utf-8;

    # Обробка роутів (index, about, contacts, projects)
    location / {
        try_files $uri $uri/ $uri.html =404;
    }

    # Кешування стилів і зображень
    location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg|woff|woff2)$ {
        expires 7d;
        add_header Cache-Control "public, no-transform";
    }
}